spring:
  application:
    name: minesweeper

  server:
    port: 8080
    error:
      include-message: always
      include-binding-errors: always

  logging:
    level:
      ru.studiotg.minesweeper: DEBUG

game:
  max_field_size: 30

cors:
  path-pattern: "/api/*"
  allowed-origins: "http://localhost:8080,https://minesweeper-test.studiotg.ru"
  allowed-methods: "POST,OPTIONS"
  max-age: 3600